version: 2
updates:

  # Keep Dockerfile up to date, batching pull requests as updated
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
